[LegalNotice]
Accepted=true

[Preferences]
WebUI\Address=*
WebUI\Port=8080
WebUI\AuthenticationEnabled=false
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
WebUI\OriginHeaderValidation=false
WebUI\AuthenticationSubnetWhitelistEnabled=false
Downloads\SavePath=/data/cache
Downloads\TempPathEnabled=false
Downloads\UseIncompleteExtension=false
Bittorrent\Session\Port=6881
Bittorrent\Session\DHT=true
Bittorrent\Session\PeX=true
Bittorrent\Session\LSD=true
Bittorrent\Session\MaxConnections=200
Bittorrent\Session\MaxUploads=20
Connection\GlobalUPLimit=32768
